### ISSUE TITLE
Please consider updating cellDancer to the latest python version

### ISSUE THREAD

**Issue by sup27606** [GuangyuWangLab2021/cellDancer#11]
Dear cellDancer team, 
Thank you so much for this very helpful program. However, I cannot run this natively on M1 Macs (arm64), since python 3.7.6 is not available for apple silicon (will never be, according to multiple forum posts). cellDancer can only be run using Rosetta emulation, which is slow. Further, I cannot integrate cellDancer easily with my main workflow in R using Seurat and reticulate, due to the platform mismatch. I was wondering, how difficult it would be to update the core functions of cellDancer to python 3.9.x and are there any plans to do so in the future?

Please note, this is not a dealbreaker, since cellDancer can still be run on newer Macs using Rosetta, its a question of convenience and to some extent, speed, especially with larger samples.

**Comment by Abclisy** [comment]
Hello! Thank you very much for the suggestion. We are working on it and evaluating the time and effort that need to be taken. We'll keep you posted if we have any updates.

**Comment by Abclisy** [comment]
Hello! The example of python==3.7.6 and the dependency versions in our installation instructions is the environment and dependencies that have been well-tested. Now we have also tested that the current functions of cellDancer are compatible with python 3.9.16 with the same requirements of dependencies. Below is the detail of setting up the environment and installing the dependencies. Hope this will be helpful to you. If you have any other questions, please don't hesitate to contact us. Thank you!

1. Download the latest source code from [github of cellDancer](https://github.com/GuangyuWangLab2021/cellDancer/tree/main) and unzip it.
2. Create a conda environment of 3.9.16 with `conda create -n cellDancer python==3.9.16`.
3. Install cellDancer with `pip install --no-deps your_path/celldancer`
4. Install the dependencies by pip install -r [requirements.txt](https://github.com/GuangyuWangLab2021/cellDancer/blob/main/requirements.txt) or install each package independently.

**Comment by sup27606** [comment]
Hello!
Thank you for your update. After following your instructions, it's running natively on m1 Mac and the velocities are identical to the version run on Rosetta. However, trying to install numpy, scikit-learn and scipy versions from requirements.txt all produced error similar to what's shown below:

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scipy
Failed to build scipy
ERROR: Could not build wheels for scipy, which is required to install pyproject.toml-based projects

I therefore installed the latest versions of these packages and they seem to work with celldancer.

**Comment by sup27606** [comment]
Closing this for now, since it's working on M1 Macs as expected.
