### ISSUE TITLE
How to export results to scvelo

### ISSUE THREAD

**Issue by sup27606** [GuangyuWangLab2021/cellDancer#12]
Dear developer,
I have calculated kinetic rates and pseudo times using cellDancer. Now I would like to do further analysis, i.e. find the top developmental genes and plot them in a heat map as function of pseudo time. I didn't see any function in cellDancer to do this (is it possible?). 

The other alternative is to feed the kinetic parameters into scvelo annData, which can estimate likelihoods on a gene basis to identify the top developmental genes. I was wondering, how to export the output from cellDancer into scvelo annData object. I already have a scvelo annData of the same system and can replace the relevant data slots. I just need to know which slots to update with cellDancer values. Thank you so much.

**Comment by Abclisy** [comment]
Hello, it's been a while since we heard back from you regarding this issue. We will be closing this issue. However, please don't hesitate to reopen it or create a new issue if you have further questions or concerns. Thank you for your understanding.

**Comment by sup27606** [comment]
So sorry that I forgot to update here. Your instructions worked perfectly. Yes, this can be closed now. Thank you very much for your prompt response.
