### ISSUE TITLE
Transfer adata format to dataframe

### ISSUE THREAD

**Issue by chen-peng-1874** [GuangyuWangLab2021/cellDancer#4]
Dear GuangyuWangLab members,

Another question is about data transfer.
I have generated adata for "scvelo" analysis, which has columns of "seurat_cluster" and U_map embeddings.
As I noticed that the syntax in your celldancer website, there is a sentence for gene list, as shown below:
```
cdutil.adata_to_df_with_embed(adata,
                              us_para=['Mu','Ms'],
                              cell_type_para='celltype',
                              embed_para='X_umap',
                              save_path='cell_type_u_s.csv',
                              **_gene_list=['Hba-x','Smim1']_**)
```
What if I want all the genes listed?
Thank you!

**Comment by Abclisy** [comment]
If in your adata, the 'seurat_cluster' is one column of adata.obs, 'X_umap' is one element of adata.obsm, you can use the codes below to transfer all genes.

```
cdutil.adata_to_df_with_embed(adata,
                              us_para=['Mu','Ms'],
                              cell_type_para='seurat_cluster',
                              embed_para='X_umap',
                              save_path='cell_type_u_s.csv')
```

Not inputting the gene_list will let adata_to_df_with_embed defaults get all genes.

**Comment by chen-peng-1874** [comment]
> If in your adata, the 'seurat_cluster' is one column of adata.obs, 'X_umap' is one element of adata.obsm, you can use the codes below to transfer all genes.
> 
> ```
> cdutil.adata_to_df_with_embed(adata,
>                               us_para=['Mu','Ms'],
>                               cell_type_para='seurat_cluster',
>                               embed_para='X_umap',
>                               save_path='cell_type_u_s.csv')
> ```
> 
> Not inputting the gene_list will let adata_to_df_with_embed defaults get all genes.

Thank you, Abclisy! I'll have a try.

**Comment by zhijunyuu** [comment]
Hey cellDancer group,

Thanks for the nice tool! I have the `adata` as follows:
`AnnData object with n_obs × n_vars = 23496 × 18964
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'donor_id', 'prob_max', 'prob_doublet', 'n_vars', 'best_singlet', 'doublet_logLikRatio', 'nCount_SCT', 'nFeature_SCT', 'pANN', 'gender', 'location', 'donors', 'SCT_snn_res.0.5', 'seurat_clusters', 'S.Score', 'G2M.Score', 'Phase', 'old.ident', 'RNA_snn_res.0.4', 'cell_types', 'batch', 'initial_size_unspliced', 'initial_size_spliced', 'initial_size'
    var: 'name', 'Accession', 'Chromosome', 'End', 'Start', 'Strand'
    uns: 'cell_types_colors'
    obsm: 'X_harmony', 'X_pca', 'X_umap'
    layers: 'ambiguous', 'matrix', 'spliced', 'unspliced'`

and I was using the `adata_to_df_with_embed` function to transfer `adata` into dataframe with the code as below:
`cdutil.adata_to_df_with_embed(adata,
                              us_para=['spliced','unspliced'],
                              cell_type_para='cell_types',
                              embed_para='X_umap',
                              save_path='cell_type_u_s.csv')`

But I got an error: `ValueError: If using all scalar values, you must pass an index`
Do you have any idea about this error? Thanks in advance!

Best,
Zhijun

**Comment by chen-peng-1874** [comment]
It seems that you don't have "Mu" and  "Ms" in your obsm.

You can process the data in scvelo, and then use cdutil.

Hope that will help you.
________________________________

**Comment by Abclisy** [comment]
Hi zhijunyuu, the codes below will help you to get the 'Mu' and 'Ms' in your 'layers' of adata.
```
# !pip install scvelo --upgrade --quiet
import scvelo as scv
scv.pp.filter_genes(adata, min_shared_counts=20)
scv.pp.normalize_per_cell(adata)
scv.pp.filter_genes_dispersion(adata, n_top_genes=2000)
scv.pp.log1p(adata)
scv.pp.filter_and_normalize(adata, min_shared_counts=20, n_top_genes=2000)
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)
```

For more information, [Data Preparation](https://guangyuwanglab2021.github.io/cellDancer_website/data_preprocessing.html) might be helpful. We will add more details about the preprocessing on our website later. Thank you!
