### ISSUE TITLE
Memory cap?

### ISSUE THREAD

**Issue by cnk113** [GuangyuWangLab2021/cellDancer#7]
Hello,

I've been trying to run cellDancer for about 150K cells, but during velocity estimation the memory explodes no matter the gene list size input. I was wondering if there was a way to cap the memory usage?

Thanks,
Chang

**Comment by Abclisy** [comment]
Hi Chang, cellDancer uses [joblib.Parallel](https://joblib.readthedocs.io/en/latest/generated/joblib.Parallel.html#joblib-parallel) to allow the prediction for multiple genes at the same time. _n_jobs_ is set to -1 by default, which means all CPUs are used. Could you please start with _n_jobs=1_ for _cd.velocity_ to see if it works or not?

If it still doesn't work, could you provide us with your usage of _cd.velocity_ along with parameters and error message? Or, if possible, providing a small subset of your data could let us repeat your problem. Thank you!

**Comment by Abclisy** [comment]
Hello, it's been a while since we heard back from you regarding this issue. We will be closing this issue. However, please don't hesitate to reopen it or create a new issue if you have further questions or concerns. Thank you for your understanding.
