### ISSUE TITLE
how can we know which gene to use?

### ISSUE THREAD

**Issue by chen-peng-1874** [GuangyuWangLab2021/cellDancer#8]
Dear GuangyuWanglab members,

I tried cellDancer, and it seems that the results are different with different gene lists.
As we can see in your representative case studies 1 and 2, you used a known gene list, to be specific, you used "gene_list=['Psd3', 'Dcx', 'Syt11', 'Ntrk2', 'Gnao1', 'Gria1', 'Dctn3', 'Map1b', 'Camk2a', 'Gpm6b', 'Sez6l', 'Evl', 'Astn1', 'Ank2', 'Klf7', 'Tbc1d16', 'Atp1a3', 'Stxbp6', 'Scn2a1', 'Lhx9', 'Slc4a4', 'Ppfia2', 'Kcnip1', 'Ptpro', 'Diaph3', 'Slc1a3', 'Cadm1', 'Mef2c', 'Sptbn1', 'Ncald'] "
for the hippocampus branch development study.
So **where are these genes come from**? Do we need to search for the branching gene first?

And if I don't use gene list, that means I am actually calculating all the gene velocities, the results are inconsistence with that in vivo.

Thanks!

**Comment by Abclisy** [comment]
Hi, we manually searched the branching genes and combined them with the reported branching gene list. If you want to study branching genes, you may also manually search for branching genes.

For your second question, could you provide more detail? Thank you!

**Comment by chen-peng-1874** [comment]
> 
Thank you! I will search for branching genes.
The second question is indeed the same as the first one. I just used all the genes, instead of the branching genes for generating velocity.
